#!/bin/bash

certbot certonly --standalone --break-my-certs \
  -d opsoro.be \
  -d www.opsoro.be \
  -d demo.opsoro.be \
  -d play.opsoro.be \
  -d forum.opsoro.be \
  -d build.opsoro.be \
  -d dev.opsoro.be \
  -d developers.opsoro.be \
  -d community.opsoro.be
