#!/bin/bash

# Stop opsoro service
service opsoro_circus stop

# Download update
git pull

source play/bin/activate
cd opsoro
python manage.py makemigrations
python manage.py migrate
deactivate

# Start opsoro service
service opsoro_circus start
service opsoro_uwsgi restart
service nginx restart
